# Generated by Django 6.1 on 2026-09-10 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'city_master',
            },
        ),
        migrations.CreateModel(
            name='DayMaster',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'day_master',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'state_master',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.citymaster')),
            ],
            options={
                'db_table': 'clinics',
            },
        ),
        migrations.CreateModel(
            name='ClinicHours',
            fields=[
                ('hours_id', models.AutoField(primary_key=True, serialize=False)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('clinic', models.ForeignKey(db_column='clinic_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
                ('day', models.ForeignKey(db_column='day_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.daymaster')),
            ],
            options={
                'db_table': 'clinic_hours',
            },
        ),
        migrations.AddField(
            model_name='citymaster',
            name='state',
            field=models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.statemaster'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('account_status', models.CharField(default='active', max_length=20)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='ClinicStaff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinic', models.ForeignKey(db_column='clinic_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'clinic_staff',
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_level', models.CharField(max_length=50)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('verification_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.admin')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'verification_log',
            },
        ),
    ]
