# Generated by Django 6.1 on 2026-09-10 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationMaster',
            fields=[
                ('qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'qualification_master',
            },
        ),
        migrations.CreateModel(
            name='SpecializationMaster',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'specialization_master',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=255)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('new_patient_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_patient_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('clinic', models.ForeignKey(db_column='clinic_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
                ('day', models.ForeignKey(db_column='day_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.daymaster')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
            options={
                'db_table': 'doctor_availability',
            },
        ),
        migrations.CreateModel(
            name='DoctorClinic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clinic', models.ForeignKey(db_column='clinic_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
            options={
                'db_table': 'doctor_clinic',
            },
        ),
        migrations.CreateModel(
            name='DoctorQualification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('qualification', models.ForeignKey(db_column='qualification_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.qualificationmaster')),
            ],
            options={
                'db_table': 'doctor_qualification',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_text', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('specialization', models.ForeignKey(db_column='specialization_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.specializationmaster')),
            ],
            options={
                'db_table': 'doctor_specialization',
            },
        ),
    ]
